if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi
export PATH=/usr/local/bin:$PATH

# The next line updates PATH for the Google Cloud SDK.
# source '/Users/cmccarte/google-cloud-sdk/path.bash.inc'

# The next line enables bash completion for gcloud.
# source '/Users/cmccarte/google-cloud-sdk/completion.bash.inc'
